//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDoc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TipoDoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdTipoDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.Cliente[] clientesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTipoDoc {
            get {
                return this.IdTipoDocField;
            }
            set {
                if ((this.IdTipoDocField.Equals(value) != true)) {
                    this.IdTipoDocField = value;
                    this.RaisePropertyChanged("IdTipoDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WindowsFormsApp1.ServiceReference1.Cliente[] clientes {
            get {
                return this.clientesField;
            }
            set {
                if ((object.ReferenceEquals(this.clientesField, value) != true)) {
                    this.clientesField = value;
                    this.RaisePropertyChanged("clientes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.TipoDoc DocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.CondImpos CondicionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((this.DNIField.Equals(value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WindowsFormsApp1.ServiceReference1.TipoDoc Doc {
            get {
                return this.DocField;
            }
            set {
                if ((object.ReferenceEquals(this.DocField, value) != true)) {
                    this.DocField = value;
                    this.RaisePropertyChanged("Doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WindowsFormsApp1.ServiceReference1.CondImpos Condicion {
            get {
                return this.CondicionField;
            }
            set {
                if ((object.ReferenceEquals(this.CondicionField, value) != true)) {
                    this.CondicionField = value;
                    this.RaisePropertyChanged("Condicion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CondImpos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CondImpos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdCondicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceReference1.Cliente[] clientesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCondicion {
            get {
                return this.IdCondicionField;
            }
            set {
                if ((this.IdCondicionField.Equals(value) != true)) {
                    this.IdCondicionField = value;
                    this.RaisePropertyChanged("IdCondicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WindowsFormsApp1.ServiceReference1.Cliente[] clientes {
            get {
                return this.clientesField;
            }
            set {
                if ((object.ReferenceEquals(this.clientesField, value) != true)) {
                    this.clientesField = value;
                    this.RaisePropertyChanged("clientes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TiposDoc del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearTipoDocumento", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoResponse CrearTipoDocumento(WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearTipoDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoResponse> CrearTipoDocumentoAsync(WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Codigo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarTipoDocumento", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoResponse EliminarTipoDocumento(WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarTipoDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoResponse> EliminarTipoDocumentoAsync(WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerListaDocResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaDoc", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.ObtenerListaDocResponse ObtenerListaDoc(WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ObtenerListaDocResponse> ObtenerListaDocAsync(WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearTipoDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearTipoDocumento", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequestBody Body;
        
        public CrearTipoDocumentoRequest() {
        }
        
        public CrearTipoDocumentoRequest(WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearTipoDocumentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.TipoDoc TiposDoc;
        
        public CrearTipoDocumentoRequestBody() {
        }
        
        public CrearTipoDocumentoRequestBody(WindowsFormsApp1.ServiceReference1.TipoDoc TiposDoc) {
            this.TiposDoc = TiposDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearTipoDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearTipoDocumentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoResponseBody Body;
        
        public CrearTipoDocumentoResponse() {
        }
        
        public CrearTipoDocumentoResponse(WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearTipoDocumentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CrearTipoDocumentoResult;
        
        public CrearTipoDocumentoResponseBody() {
        }
        
        public CrearTipoDocumentoResponseBody(string CrearTipoDocumentoResult) {
            this.CrearTipoDocumentoResult = CrearTipoDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarTipoDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarTipoDocumento", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequestBody Body;
        
        public EliminarTipoDocumentoRequest() {
        }
        
        public EliminarTipoDocumentoRequest(WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarTipoDocumentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Codigo;
        
        public EliminarTipoDocumentoRequestBody() {
        }
        
        public EliminarTipoDocumentoRequestBody(string Codigo) {
            this.Codigo = Codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarTipoDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarTipoDocumentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoResponseBody Body;
        
        public EliminarTipoDocumentoResponse() {
        }
        
        public EliminarTipoDocumentoResponse(WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarTipoDocumentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarTipoDocumentoResult;
        
        public EliminarTipoDocumentoResponseBody() {
        }
        
        public EliminarTipoDocumentoResponseBody(string EliminarTipoDocumentoResult) {
            this.EliminarTipoDocumentoResult = EliminarTipoDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaDoc", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequestBody Body;
        
        public ObtenerListaDocRequest() {
        }
        
        public ObtenerListaDocRequest(WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerListaDocRequestBody {
        
        public ObtenerListaDocRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ObtenerListaDocResponseBody Body;
        
        public ObtenerListaDocResponse() {
        }
        
        public ObtenerListaDocResponse(WindowsFormsApp1.ServiceReference1.ObtenerListaDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerListaDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.TipoDoc[] ObtenerListaDocResult;
        
        public ObtenerListaDocResponseBody() {
        }
        
        public ObtenerListaDocResponseBody(WindowsFormsApp1.ServiceReference1.TipoDoc[] ObtenerListaDocResult) {
            this.ObtenerListaDocResult = ObtenerListaDocResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WebService1Soap>, WindowsFormsApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.CrearTipoDocumento(WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequest request) {
            return base.Channel.CrearTipoDocumento(request);
        }
        
        public string CrearTipoDocumento(WindowsFormsApp1.ServiceReference1.TipoDoc TiposDoc) {
            WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequest inValue = new WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequestBody();
            inValue.Body.TiposDoc = TiposDoc;
            WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).CrearTipoDocumento(inValue);
            return retVal.Body.CrearTipoDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.CrearTipoDocumentoAsync(WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequest request) {
            return base.Channel.CrearTipoDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoResponse> CrearTipoDocumentoAsync(WindowsFormsApp1.ServiceReference1.TipoDoc TiposDoc) {
            WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequest inValue = new WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.CrearTipoDocumentoRequestBody();
            inValue.Body.TiposDoc = TiposDoc;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).CrearTipoDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.EliminarTipoDocumento(WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequest request) {
            return base.Channel.EliminarTipoDocumento(request);
        }
        
        public string EliminarTipoDocumento(string Codigo) {
            WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequest inValue = new WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequestBody();
            inValue.Body.Codigo = Codigo;
            WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).EliminarTipoDocumento(inValue);
            return retVal.Body.EliminarTipoDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.EliminarTipoDocumentoAsync(WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequest request) {
            return base.Channel.EliminarTipoDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoResponse> EliminarTipoDocumentoAsync(string Codigo) {
            WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequest inValue = new WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.EliminarTipoDocumentoRequestBody();
            inValue.Body.Codigo = Codigo;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).EliminarTipoDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.ObtenerListaDocResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.ObtenerListaDoc(WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequest request) {
            return base.Channel.ObtenerListaDoc(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.TipoDoc[] ObtenerListaDoc() {
            WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequest inValue = new WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequestBody();
            WindowsFormsApp1.ServiceReference1.ObtenerListaDocResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).ObtenerListaDoc(inValue);
            return retVal.Body.ObtenerListaDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ObtenerListaDocResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.ObtenerListaDocAsync(WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequest request) {
            return base.Channel.ObtenerListaDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ObtenerListaDocResponse> ObtenerListaDocAsync() {
            WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequest inValue = new WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.ObtenerListaDocRequestBody();
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).ObtenerListaDocAsync(inValue);
        }
    }
}
