//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HolaSaludameResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HolaSaludame", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.HolaSaludameResponse HolaSaludame(WindowsFormsApp1.ServiceReference1.HolaSaludameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HolaSaludame", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.HolaSaludameResponse> HolaSaludameAsync(WindowsFormsApp1.ServiceReference1.HolaSaludameRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DividirNResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DividirN", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.DividirNResponse DividirN(WindowsFormsApp1.ServiceReference1.DividirNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DividirN", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.DividirNResponse> DividirNAsync(WindowsFormsApp1.ServiceReference1.DividirNRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HolaSaludameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HolaSaludame", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.HolaSaludameRequestBody Body;
        
        public HolaSaludameRequest() {
        }
        
        public HolaSaludameRequest(WindowsFormsApp1.ServiceReference1.HolaSaludameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HolaSaludameRequestBody {
        
        public HolaSaludameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HolaSaludameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HolaSaludameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.HolaSaludameResponseBody Body;
        
        public HolaSaludameResponse() {
        }
        
        public HolaSaludameResponse(WindowsFormsApp1.ServiceReference1.HolaSaludameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HolaSaludameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HolaSaludameResult;
        
        public HolaSaludameResponseBody() {
        }
        
        public HolaSaludameResponseBody(string HolaSaludameResult) {
            this.HolaSaludameResult = HolaSaludameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DividirNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DividirN", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.DividirNRequestBody Body;
        
        public DividirNRequest() {
        }
        
        public DividirNRequest(WindowsFormsApp1.ServiceReference1.DividirNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DividirNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Nro;
        
        public DividirNRequestBody() {
        }
        
        public DividirNRequestBody(int Nro) {
            this.Nro = Nro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DividirNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DividirNResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.DividirNResponseBody Body;
        
        public DividirNResponse() {
        }
        
        public DividirNResponse(WindowsFormsApp1.ServiceReference1.DividirNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DividirNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DividirNResult;
        
        public DividirNResponseBody() {
        }
        
        public DividirNResponseBody(string DividirNResult) {
            this.DividirNResult = DividirNResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WebService1Soap>, WindowsFormsApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.HolaSaludameResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.HolaSaludame(WindowsFormsApp1.ServiceReference1.HolaSaludameRequest request) {
            return base.Channel.HolaSaludame(request);
        }
        
        public string HolaSaludame() {
            WindowsFormsApp1.ServiceReference1.HolaSaludameRequest inValue = new WindowsFormsApp1.ServiceReference1.HolaSaludameRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.HolaSaludameRequestBody();
            WindowsFormsApp1.ServiceReference1.HolaSaludameResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).HolaSaludame(inValue);
            return retVal.Body.HolaSaludameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.HolaSaludameResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.HolaSaludameAsync(WindowsFormsApp1.ServiceReference1.HolaSaludameRequest request) {
            return base.Channel.HolaSaludameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.HolaSaludameResponse> HolaSaludameAsync() {
            WindowsFormsApp1.ServiceReference1.HolaSaludameRequest inValue = new WindowsFormsApp1.ServiceReference1.HolaSaludameRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.HolaSaludameRequestBody();
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).HolaSaludameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.DividirNResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.DividirN(WindowsFormsApp1.ServiceReference1.DividirNRequest request) {
            return base.Channel.DividirN(request);
        }
        
        public string DividirN(int Nro) {
            WindowsFormsApp1.ServiceReference1.DividirNRequest inValue = new WindowsFormsApp1.ServiceReference1.DividirNRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.DividirNRequestBody();
            inValue.Body.Nro = Nro;
            WindowsFormsApp1.ServiceReference1.DividirNResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).DividirN(inValue);
            return retVal.Body.DividirNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.DividirNResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.DividirNAsync(WindowsFormsApp1.ServiceReference1.DividirNRequest request) {
            return base.Channel.DividirNAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.DividirNResponse> DividirNAsync(int Nro) {
            WindowsFormsApp1.ServiceReference1.DividirNRequest inValue = new WindowsFormsApp1.ServiceReference1.DividirNRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.DividirNRequestBody();
            inValue.Body.Nro = Nro;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).DividirNAsync(inValue);
        }
    }
}
